#!/bin/bash

echo -n "Please enter the evernode number (ordinal inside this server): "

read evernode_number

echo -n "Please enter the host number: "

read host_number

qm clone 9000 10$evernode_number --name evernode-$evernode_number-costa-$host_number

qm set 10$evernode_number --sshkey ~/.ssh/id_rsa.pub

qm set 10$evernode_number --ipconfig0 ip=192.168.1.10$evernode_number/24,gw=192.168.1.1

qm start $evernode_number

sleep 10

ssh-keygen -f "/root/.ssh/known_hosts" -R "192.168.10$evernode_number"

sudo ssh -o StrictHostKeyChecking=accept-new evernode@192.168.1.10$evernode_number "sudo chown evernode /etc/hosts"

sudo ssh -o StrictHostKeyChecking=accept-new evernode@192.168.1.10$evernode_number "sudo chown evernode /home/"

sudo ssh -o StrictHostKeyChecking=accept-new evernode@192.168.1.10$evernode_number "sudo echo \"127.0.0.1 $host_number.genesis-one-seven-1.online\" >> /etc/hosts"

ssh -o StrictHostKeyChecking=accept-new evernode@192.168.1.10$evernode_number "sudo fallocate -l 4G /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile && sudo cp /etc/fstab /etc/fstab.bak && echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab"

